spring.application.name=pagos-service
server.port=8083

# Eureka
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
eureka.instance.prefer-ip-address=true

# MongoDB
spring.mongodb.uri=mongodb://admin:admin@mongodb:27017/pagos?authSource=admin
