spring.application.name=pagos-service
server.port=8083

# Eureka
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
eureka.instance.prefer-ip-address=true

# MongoDB
spring.data.mongodb.uri=mongodb://admin:admin@mongodb:27017/pagos?authSource=admin

# Kafka retry topics
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
broker.topics.payments=${BROKER_TOPICS_PAYMENTS:payments_retry_jobs}
